baseURL = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Brennhagen.no"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = ""

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
  [languages.no]
    languageName = "Norsk"
    weight = 20
  [languages.nl]
    languageName = "Nederlands"
    weight = 20
  [languages.fr]
    languageName = "Français"
    weight = 20
  [languages.de]
    languageName = "Deutsch"
    weight = 20
[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:ole@brennhagen.no"

    [[params.links]]
        icon = "android"
        title = "pwd.cat"
        url = "https://pwd.cat"
